# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_USB_ROLE_SWITCH)		+= roles.o
roles-y					:= class.o
obj-$(CONFIG_USB_ROLES_INTEL_XHCI)	+= intel-xhci-usb-role-switch.o
obj-$(CONFIG_IMX8_USB_ROLES_SW)	+= imx8-role-switch.o
